# Generated by Django 4.0.2 on 2022-02-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('school_nu', models.CharField(default='1', max_length=30, primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=500, null=True)),
                ('school_rule', models.CharField(blank=True, max_length=500, null=True)),
                ('school_education_system', models.CharField(blank=True, max_length=50, null=True)),
                ('school_Quarter', models.CharField(blank=True, max_length=500, null=True)),
                ('school_manager_name', models.CharField(blank=True, max_length=500, null=True)),
                ('school_manager_mobile', models.CharField(blank=True, max_length=500, null=True)),
                ('longitude', models.IntegerField(default=1, max_length=30)),
                ('latitude', models.IntegerField(default=1, max_length=30)),
            ],
        ),
    ]
