# Generated by Django 4.0.2 on 2022-02-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='School',
            name='latitude',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='School',
            name='longitude',
            field=models.IntegerField(default=1),
        ),
    ]
