# Generated by Django 4.0.2 on 2022-02-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_latitude_alter_school_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='School',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='School',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
