# Generated by Django 4.0.2 on 2022-03-24 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schools', '0006_school_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_note',
            fields=[
                ('school_nu', models.CharField(default='1', max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('subject', models.TextField(null=True)),
                ('private', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
