# Generated by Django 4.0.2 on 2022-04-13 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Schools', '0010_alter_note_created_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.TextField(null=True, verbose_name='نص الملاحظة'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان الملاحظة'),
        ),
        migrations.AlterField(
            model_name='school_note',
            name='created_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
