# Generated by Django 4.0.2 on 2022-04-14 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schools', '0011_alter_note_created_user_alter_note_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created_user',
            field=models.CharField(max_length=200),
        ),
    ]
