# Generated by Django 4.0.2 on 2022-05-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_alter_note_created_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='School',
            name='total_class',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='School',
            name='total_student',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
