# Generated by Django 4.0.4 on 2023-09-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_remove_school_note_created_user_delete_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeDensity',
            fields=[
                ('office_nu', models.CharField(default='1', max_length=30, primary_key=True, serialize=False)),
                ('office_name', models.CharField(blank=True, max_length=500, null=True)),
                ('office_density', models.IntegerField(default=0)),
                ('childHold_density', models.IntegerField(default=0)),
                ('primary_density', models.IntegerField(default=0)),
                ('elementry_density', models.IntegerField(default=0)),
                ('secondary_density', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='BuildingState',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='MainSchool',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='adminstration',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='density',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='independence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
