# Generated by Django 4.0.4 on 2023-09-11 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_officedensity_school_buildingstate_school_mainschool_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='officedensity',
            old_name='childHold_density',
            new_name='childhold_density',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='BuildingState',
            new_name='building_state',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='MainSchool',
            new_name='main_school',
        ),
    ]
