# Generated by Django 4.0.2 on 2022-06-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_rename_childhold_density_officedensity_childhold_density_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_type', models.CharField(blank=True, max_length=500, null=True)),
                ('project_name', models.CharField(blank=True, max_length=500, null=True)),
                ('project_gender', models.CharField(blank=True, max_length=50, null=True)),
                ('project_class_count', models.IntegerField(default=0)),
                ('project_capacity', models.IntegerField(default=0)),
                ('project_completion_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('project_office', models.CharField(blank=True, max_length=500, null=True)),
                ('project_longitude', models.FloatField(blank=True, null=True)),
                ('project_latitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
