# Generated by Django 4.0.2 on 2022-06-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Project',
            name='project_latitude',
        ),
        migrations.RemoveField(
            model_name='Project',
            name='project_longitude',
        ),
        migrations.AddField(
            model_name='Project',
            name='project_location',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
