# Generated by Django 4.0.2 on 2022-06-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_remove_project_project_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Project',
            name='project_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
