# Generated by Django 4.0.4 on 2023-09-11 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_project_project_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='school_Quarter',
            new_name='school_quarter',
        ),
    ]
