# Generated by Django 4.0.4 on 2023-09-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_rename_school_quarter_school_school_quarter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['school_name']},
        ),
    ]
