# Generated by Django 4.0.4 on 2023-09-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0022_alter_school_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
    ]
